-- Backfill subscription↔invoice links for invoices auto-generated by the
-- /subscricoes/nova flow. Until this migration, that path created the
-- invoice but never wrote `invoices.subscription_id` nor stamped
-- `invoice_items.source_subscription_item_id`, leaving the relationship
-- broken in both directions:
--   - Editing the subscription did NOT propagate to the invoice (the
--     sync hook in useUpdateSubscriptionItem reads from
--     subscription_items.source_invoice_item_id, which was empty).
--   - Editing the invoice did NOT propagate to the subscription (the
--     sync hook in useUpdateInvoiceItems reads from
--     invoice_items.source_subscription_item_id, also empty).
--   - InvoiceDetail's "Subscrições associadas" section was empty too,
--     because invoices.subscription_id was NULL.
--
-- Heuristic match: the auto-issued invoice always carries a marker note
-- of the form "Fatura gerada automaticamente da subscrição: <name>".
-- We pair invoice→subscription on (client_id, sub.name) extracted from
-- the note, but only when the match is unambiguous (exactly one active
-- candidate). Items are paired by description: the subscription_item's
-- description is a prefix of the invoice_item's description (the cron
-- and Subscriptions.tsx both append " — <Mês> <Ano>"). Setup items
-- match exactly because both sides emit "Setup <name>".
--
-- This migration is idempotent: it never overwrites an existing link.

do $$
declare
  inv record;
  matched_sub_id uuid;
  ii record;
  matched_si_id uuid;
  sub_name text;
  prefix text;
begin
  for inv in
    select i.id, i.client_id, i.notes
    from public.invoices i
    where i.subscription_id is null
      and i.deleted_at is null
      and i.notes is not null
      and i.notes like 'Fatura gerada automaticamente da subscrição: %'
  loop
    -- Extract the sub name from the marker note. Trim trailing
    -- whitespace; a multi-line note would only have the first line
    -- match the prefix, so we cap on newline as well.
    sub_name := regexp_replace(
      inv.notes,
      '^Fatura gerada automaticamente da subscrição: ([^\n\r]+).*$',
      '\1',
      's'
    );
    sub_name := btrim(sub_name);

    if sub_name is null or sub_name = '' then
      continue;
    end if;

    -- Look up exactly one active sub matching client + name. If two
    -- subs share the same name on the same client (rare but
    -- possible), skip — manual linking is safer than guessing.
    select s.id into matched_sub_id
    from public.subscriptions s
    where s.client_id = inv.client_id
      and s.name = sub_name
      and s.deleted_at is null
    limit 2;

    if matched_sub_id is null then
      continue;
    end if;

    -- Reject ambiguous matches (more than one sub with same name).
    if (
      select count(*) from public.subscriptions s
      where s.client_id = inv.client_id
        and s.name = sub_name
        and s.deleted_at is null
    ) > 1 then
      continue;
    end if;

    -- Wire the parent reference on the invoice.
    update public.invoices
    set subscription_id = matched_sub_id
    where id = inv.id;

    -- Link each invoice_item to the most plausible sub_item. We
    -- prefer prefix-match on description because the recurring line
    -- always has " — <Mês> <Ano>" appended; the setup line keeps the
    -- raw "Setup <name>" form on both sides.
    for ii in
      select id, description
      from public.invoice_items
      where invoice_id = inv.id
        and source_subscription_item_id is null
    loop
      matched_si_id := null;

      -- 1) Exact match (handles setup items and any other line that
      --    didn't get a date suffix appended).
      select si.id into matched_si_id
      from public.subscription_items si
      where si.subscription_id = matched_sub_id
        and si.description = ii.description
      limit 1;

      -- 2) Prefix match: sub_item description is a prefix of the
      --    invoice_item description (the trailing " — Mês Ano" is the
      --    only difference for the recurring line).
      if matched_si_id is null then
        select si.id into matched_si_id
        from public.subscription_items si
        where si.subscription_id = matched_sub_id
          and ii.description like si.description || ' — %'
        limit 1;
      end if;

      -- 3) Last resort: when there's only one sub_item on the sub,
      --    just use it. Avoids leaving the invoice fully orphaned
      --    when the description was hand-edited.
      if matched_si_id is null then
        if (
          select count(*) from public.subscription_items si2
          where si2.subscription_id = matched_sub_id
        ) = 1 then
          select si.id into matched_si_id
          from public.subscription_items si
          where si.subscription_id = matched_sub_id
          limit 1;
        end if;
      end if;

      if matched_si_id is not null then
        update public.invoice_items
        set source_subscription_item_id = matched_si_id
        where id = ii.id;

        -- Inverse link: only fill if still empty so we never
        -- overwrite a NewInvoice-style link from a previous flow.
        update public.subscription_items
        set source_invoice_item_id = ii.id
        where id = matched_si_id
          and source_invoice_item_id is null;
      end if;
    end loop;
  end loop;
end $$;
