-- One-off backfill: populate service_start_date / service_end_date on
-- existing invoice_items that have NULL dates but are linked to a
-- subscription. These columns were added by
-- 20260416100000_invoice_item_dates.sql and only started being filled
-- in by the cron after 20260510082500_cron_invoice_service_dates.sql.
-- Every invoice generated before that — and any auto-generated invoice
-- between then and the fix migration (20260525200000) that the broken
-- cron failed to produce — has the columns NULL, which means the
-- InvoiceDetail page and the PDF (both render `period` via
-- formatInvoiceItemPeriod when set) show no service period under each
-- line. Backfilling makes the history consistent with what new
-- auto-generated invoices look like going forward.
--
-- Inference strategy (matches user intuition: a recurring line on an
-- invoice issued in May 2026 covers the calendar month of May 2026):
--
--   * Only touch invoice_items where:
--       - service_start_date IS NULL AND service_end_date IS NULL
--       - the parent invoice has subscription_id IS NOT NULL (it was
--         generated by the cron, or manually created for a subscription)
--       - if the line is linked back to a subscription_item, that
--         item's `kind` is in ('recurring','addon'). Setup lines stay
--         NULL because the period columns are not meaningful for them
--         (matches what the live cron does today).
--   * Use the invoice's `issue_date` as the anchor and the
--     subscription's `frequency` to derive the calendar period:
--       - monthly   → first/last day of the calendar month
--       - quarterly → first/last day of the calendar quarter
--       - yearly    → Jan 1 / Dec 31 of the calendar year
--     This is intentionally calendar-aligned (rather than re-deriving
--     from next_billing_date − offset_days, which would require state
--     we no longer have on disk) because it matches how the
--     description suffix is rendered (e.g. "— Maio 2026").
--   * For the EARLIEST invoice of a subscription (ordered by
--     issue_date asc, created_at asc), the service_start is pinned to
--     `sub.start_date` instead of the start of the calendar period —
--     this mirrors the `is_first_invoice` branch of the cron, which
--     bills a possibly-partial first period from the subscription's
--     actual start date.
--
-- Idempotent: the WHERE clause skips rows already populated, so this
-- migration can be re-run safely without overwriting any manual edits
-- the user might have made via the InvoiceDetail editor.
--
-- Soft-deleted invoices are excluded — restoring them later is rare,
-- and not back-filling those keeps the operation tightly scoped to
-- visible data.

with first_invoice_per_sub as (
  -- Picks the earliest invoice per subscription. The cron's
  -- `is_first_invoice` branch keys off subscriptions.first_invoice_generated_at,
  -- which is a timestamp (not an invoice id), so we approximate by
  -- choosing the chronologically-first invoice. Tie-break on
  -- created_at to be deterministic when two invoices share a date.
  select distinct on (i.subscription_id)
    i.subscription_id,
    i.id as invoice_id
  from public.invoices i
  where i.subscription_id is not null
    and i.deleted_at is null
  order by i.subscription_id, i.issue_date asc, i.created_at asc
),
derived as (
  select
    ii.id as item_id,
    i.issue_date,
    s.start_date as sub_start_date,
    s.frequency,
    (fips.invoice_id = i.id) as is_first_invoice
  from public.invoice_items ii
  join public.invoices i        on i.id = ii.invoice_id
  join public.subscriptions s   on s.id = i.subscription_id
  left join first_invoice_per_sub fips on fips.subscription_id = s.id
  where ii.service_start_date is null
    and ii.service_end_date   is null
    and i.deleted_at  is null
    and s.deleted_at  is null
    -- Either the line has no link back to a subscription_item (legacy
    -- auto-generated rows from before the link column existed), OR
    -- the linked subscription_item is recurring/addon. Setup lines
    -- never get period dates.
    and (
      ii.source_subscription_item_id is null
      or exists (
        select 1
        from public.subscription_items si
        where si.id = ii.source_subscription_item_id
          and si.kind in ('recurring', 'addon')
      )
    )
)
update public.invoice_items ii
set
  service_start_date = case
    when d.is_first_invoice then d.sub_start_date
    when d.frequency = 'monthly'   then date_trunc('month',   d.issue_date::timestamp)::date
    when d.frequency = 'quarterly' then date_trunc('quarter', d.issue_date::timestamp)::date
    when d.frequency = 'yearly'    then date_trunc('year',    d.issue_date::timestamp)::date
  end,
  service_end_date = case
    when d.frequency = 'monthly'   then (date_trunc('month',   d.issue_date::timestamp) + interval '1 month'  - interval '1 day')::date
    when d.frequency = 'quarterly' then (date_trunc('quarter', d.issue_date::timestamp) + interval '3 months' - interval '1 day')::date
    when d.frequency = 'yearly'    then (date_trunc('year',    d.issue_date::timestamp) + interval '1 year'   - interval '1 day')::date
  end
from derived d
where ii.id = d.item_id;
